package ru.dm_ushakov.alice.aliceskill.capabilities.model

import com.fasterxml.jackson.annotation.JsonValue

enum class Mode(@get:JsonValue val modeName: String) {
    Auto("auto"),
    Eco("eco"),
    Turbo("turbo"),
    Cool("cool"),
    Dry("dry"),
    FanOnly("fan_only"),
    Heat("heat"),
    Preheat("preheat"),
    High("high"),
    Low("low"),
    Medium("medium"),
    Max("max"),
    Min("min"),
    Fast("fast"),
    Slow("slow"),
    Express("express"),
    Normal("normal"),
    Quiet("quiet"),
    Horizontal("horizontal"),
    Stationary("stationary"),
    Vertical("vertical"),
    One("one"),
    Two("two"),
    Three("three"),
    Four("four"),
    Five("five"),
    Six("six"),
    Seven("seven"),
    Eight("eight"),
    Nine("nine"),
    Ten("ten"),
    Americano("americano"),
    Cappuccino("cappuccino"),
    DoubleEspresso("double_espresso"),
    Espresso("espresso"),
    Latte("latte"),
    BlackTea("black_tea"),
    FlowerTea("flower_tea"),
    GreenTea("green_tea"),
    HerbalTea("herbal_tea"),
    OolongTea("oolong_tea"),
    PuerhTea("puerh_tea"),
    RedTea("red_tea"),
    WhiteTea("white_tea"),
    Glass("glass"),
    Intensive("intensive"),
    PreRinse("pre_rinse"),
    Aspic("aspic"),
    BabyFood("baby_food"),
    Baking("baking"),
    Bread("bread"),
    Boiling("boiling"),
    Cereals("cereals"),
    Cheesecake("cheesecake"),
    DeepFryer("deep_fryer"),
    Dessert("dessert"),
    Fowl("fowl"),
    Frying("frying"),
    Macaroni("macaroni"),
    MilkPorridge("milk_porridge"),
    Multicooker("multicooker"),
    Pasta("pasta"),
    Pilaf("pilaf"),
    Pizza("pizza"),
    Sauce("sauce"),
    SlowCook("slow_cook"),
    Soup("soup"),
    Steam("steam"),
    Stewing("stewing"),
    Vacuum("vacuum"),
    Yogurt("yogurt");

    override fun toString() = modeName

    companion object {
        private val nameToMode: Map<String, Mode> = values().associateBy { it.modeName }
        fun getMode(modeName: String) = nameToMode[modeName] ?: error("Unknown mode - $modeName!")
    }
}